# -*- coding: utf-8 -*-
"""AI_Chat_Log_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXA330VrY2pWDmMiqnws_6nJyVnCnR-K
"""

def parseChatLog(filePath):
  ai_messages = []
  user_messages = []

  with open(filePath, 'r', encoding='utf-8') as a:
        for l in a:
            l = l.strip()
            if l.startswith("User:"):
                user_messages.append(l[len("User:"):].strip())
            elif l.startswith("AI:"):
                ai_messages.append(l[len("AI:"):].strip())

  return user_messages, ai_messages